services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: unless-stopped
    volumes:
      - uptime-kuma-data:/app/data
    networks:
      - internal

volumes:
  uptime-kuma-data:

networks:
  internal:
    # Docker Compose expects the network to already exist - won't create or delete it after docker compose up/down
    external: true
